### ISSUE TITLE
Error during deployment

### ISSUE THREAD

**Issue by drjayvee** [Azure-Samples/laravel-tasks#20]
I've been following along with [the tutorial](https://docs.microsoft.com/en-us/azure/app-service/tutorial-php-mysql-app?pivots=platform-linux#push-to-azure-from-git).

When first `git push`ing the repo to azure, I run into this problem:
```
...
remote: Copying file: 'config/mail.php'
remote: Omitting next output lines...
remote: Running composer install
remote: ...
remote: Loading composer repositories with package information
remote: Installing dependencies (including require-dev) from lock file
remote:
remote:
remote:   [ErrorException]
remote:   "continue" targeting switch is equivalent to "break". Did you mean to use "continue 2"?
remote:
remote:
remote: install [--prefer-source] [--prefer-dist] [--dry-run] [--dev] [--no-dev] [--no-custom-installers] [--no-autoloader] [--no-scripts] [--no-progress] [--no-suggest] [-v|vv|vvv|--verbose] [-o|--optimize-autoloader] [-a|--classmap-authoritative] [--apcu-autoloader] [--ignore-platform-reqs] [--] [<packages>]...
remote:
remote: An error has occurred during web site deployment.
remote: composer failed
remote: Deployment Logs : 'https://my.scm.azurewebsites.net/newui/jsonviewer?view_url=/api/deployments/somelonghash/log'
To https://my.scm.azurewebsites.net/my.git
 * [new branch]      HEAD -> master
```

By the way, the section [Create a web app](https://docs.microsoft.com/en-us/azure/app-service/tutorial-php-mysql-app?pivots=platform-linux#create-a-web-app) says
> The runtime is set to PHP|7.0

and yet the Azure CLI command below it sets `--runtime "PHP|7.3"`

**Comment by drjayvee** [comment]
After changing the runtime to PHP 7.2, the app deployed successfully.

Also see [this issue](azure-docs/issues/67392) about the doc's inconsistency about the runtime.

**Comment by cephalin** [comment]
https://github.com/MicrosoftDocs/azure-docs/issues/67392
