### ISSUE TITLE
Root level .htaccess to redirect to public subdirectory does not work

### ISSUE THREAD

**Issue by dpaanlka** [Azure-Samples/laravel-tasks#6]
The root level .htaccess file in this sample project does not work for me with a fresh Laravel 5.7 instillation on Azure Web App (Linux). Accessing the Laravel registration or login pages resulted in 404 on css and js resources. I found the below line needs to be modified:

`RewriteRule ^.*$ /public/$1 [NC,L,QSA]`

Replacing it with the following works:

`RewriteRule ^(.*)$ /public/$1 [NC,L,QSA]`

This fixes the problem, however I also noticed that directly accessing mydomain.com/public is still also possible. I'm not sure how to prevent accessing mydomain.com/public in the browser while also allowing mydomain.com to serve public subdirectory content. I suppose this isn't an emergency, but I'd rather not have both working. Ideas appreciated.

**Comment by cephalin** [comment]
This is an old issue that has since been fixed in the repo.
